### ISSUE TITLE
Please add Dataset

### ISSUE THREAD

**Issue by PiyushTewari2** [vfinotti/flower-or-crops-cnn-classification-pytorch#1]
Not able to find the dataset on which the model is trained. Please provide the train, valid and test dataset.
Thank you

**Comment by vfinotti** [comment]
Hello Piyush,

Unfortunately I could not provide the datasets since they were scrapped from the internet and, therefore, could be protected by copyright. However, I did uploaded the scripts I used to download the images and create them. Hopefully they might still work today, (or perhaps with minor modifications).

https://github.com/vfinotti/scrapy-flower-images-crawler

**Comment by vfinotti** [comment]
(closed by accident, feel free to reach me out in case of any questions)

**Comment by PiyushTewari2** [comment]
Thank you Vitor, that helped a lot
